theme: jekyll-theme-midnight
relative_links:
  enabled: true
  collections: true
include:
  - README.md
analytics-id: "G-0NQTETHKV5"
output:
  html_document:
    includes: 
      in_header: include.html
